### ISSUE TITLE
Basic running errors/questions

### ISSUE THREAD

**Issue by bloodconfetti** [radiolarian/AO3Scraper#15] opened 2021-02-28 23:34 UTC
Sorry for the vague header.

Issue 1: I tried running this: `python ao3_work_ids.py "https://archiveofourown.org/works?utf8=%E2%9C%93&work_search%5Bsort_column%5D=revised_at&work_search%5Bother_tag_names%5D=&exclude_work_search%5Barchive_warning_ids%5D%5B%5D=18&work_search%5Bexcluded_tag_names%5D=&work_search%5Bcrossover%5D=&work_search%5Bcomplete%5D=&work_search%5Bwords_from%5D=&work_search%5Bwords_to%5D=&work_search%5Bdate_from%5D=&work_search%5Bdate_to%5D=&work_search%5Bquery%5D=&work_search%5Blanguage_id%5D=&commit=Sort+and+Filter&tag_id=IT+%28Movies+-+Muschietti%29" --out_csv itworks`

I think it worked the first time, after I installed lxml. It created a spreadsheet, but honestly it looked like the spreadsheet was the above URL over and over for 1000+ lines (each with a line in between). I tried to run the second command code:
`python ao3_get_fanfics.py itworks.csv`
And received:
```
C:\Users\[REDACTED]\ao3_get_fanfics.py:269: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if restart is '':
Writing a header row for the csv.
Traceback (most recent call last):
  File "C:\Users\[REDACTED]\ao3_get_fanfics.py", line 292, in <module>
    main()
  File "C:\Users\[REDACTED]\ao3_get_fanfics.py", line 267, in main
    with open(csv_fname, 'r+') as f_in:
PermissionError: [Errno 13] Permission denied: 'itworks.csv'
```

Issue 2: I noticed one of those spam fics with a ton of tags so I refreshed and it had been reported, so I thought to run the first command again just to make sure it wasn't included in my scrape. But this somehow resulted in a spreadsheet where there was one line, all in foreign characters and OpenOffice telling me that my sheet was broken because of too many characters. This broke my original spreadsheet somehow?

[ao3scrapeerror.zip](https://github.com/radiolarian/AO3Scraper/files/6058331/ao3scrapeerror.zip)

ETA: Adding a folder where I have the spreadsheet working again, but the links on it lead to nowhere because of coding tagged on at the end.
[itworks links unusable.zip](https://github.com/radiolarian/AO3Scraper/files/6058658/itworks.links.unusable.zip)

**Comment by ssterman** [comment] 2021-03-02 01:19
Issue 1 -- The format of the output of ao3_work_ids.py is <work_id, url>, so the file is correct.  (The url records the search page it was found on, since search results are paginated.)  Next, the SyntaxWarning is a new warning with Python 3.8 -- you can ignore it.  The PermissionError is likely an issue with your file settings -- the scraper cannot access the itworks.csv.  Try setting the permissions on that file so anyone can read it.  

Issue 2: You can remove an id manually from the scraped csvs, which is faster than rerunning the whole scrape.  I can't reproduce your error regarding the foreign characters or the broken links.  All the links appear to work, and all spreadsheets open for me.  Try opening in a text editor rather than in OpenOffice?

**Comment by bloodconfetti** [comment] 2021-03-02 05:45
My permissions were okay, so it looks like all I needed to do was change the default program with which the file opened. Thank you so much for the assistance!!

I am realizing at this point that I may not fully understand how to actually access the fics once they're scraped. Am I missing documentation/guidance on that?

Thank you, again.

**Comment by ssterman** [comment] 2021-03-02 15:15
The fic text will be in the final column of the output csv from ao3_get_fanfics.py.  If you want them in separate text documents, the extras folder has a script called csv_to_txts.py that will do that.

**Comment by bloodconfetti** [comment] 2021-03-02 18:47
I put in:`C:\Users\Jack>csv_to_txts.py fanfics.csv
Traceback (most recent call last):
  File "C:\Users\Jack\csv_to_txts.py", line 40, in <module>
    main()
  File "C:\Users\Jack\csv_to_txts.py", line 34, in main
    next(rd)  # skip the header row
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)`
I'm sorry! Was I not supposed to open the document? Did I ruin the ability to move them into separate docs?

My other concern is that there are 15566 fics in the URL I used, but I really feel like it may have only scratched the surface. I guess I'll know better if I can get the fics separated and see exactly how many files it creates. I did have some Denied Access issues, but I couldn't locate the specific Fic IDs to check if they were locked. It seemed to be more of a timing out by AO3 issue. So I know that it didn't get all of them. But I really don't know that it got more than 1000, even with that awareness.

Thank you so much for your help, as always, and for this code!

**Comment by ssterman** [comment] 2021-03-03 01:38
I googled your error message, which is something I recommend trying first when you run into these problems.  If you are running a recent version of Python (which it seems you are), it may be related to a change in the file opening settings.  Try changing 'rb' on line 29 to 'rt' and see if it works ([from this source](https://stackoverflow.com/questions/8515053/csv-error-iterator-should-return-strings-not-bytes)). 

Access denied fic ids should be recorded in the auto-generated error file.  If AO3 is timing out, you can retry those specific ids or add some delays in the code to try and let it load.  You can count the number of fics you got by checking how many lines your output csv has; each line is a separate fic, and it will only write a line if it successfully got a fic. 

You're welcome!

**Comment by bloodconfetti** [comment] 2021-03-03 02:08
So now I've got the following error: `Traceback (most recent call last):
  File "C:\Users\Jack\csv_to_txts.py", line 40, in <module>
    main()
  File "C:\Users\Jack\csv_to_txts.py", line 36, in main
    work_id = row[0]
IndexError: list index out of range`

And reading this page (https://careerkarma.com/blog/python-indexerror-list-index-out-of-range/) I'm wondering if it's saying I should change the .py file code from this:
`		for row in rd:
			work_id = row[0]
			with open(folder_name + "/" + row[0] + ".txt", "w") as text_file:
				text_file.write(row[-1])

main()`
to this:
`		for row in rd:
			work_id = row[0]
			with open in range(folder_name + "/" + (row) + ".txt", "w") as text_file:
				text_file.write(row[-1])

main()`

Sorry, I find it confusing trying to apply the scenario in the article to this one. If you would rather only answer these questions for a fee (or not at all) just let me know. I can try to get help elsewhere.

**Comment by ssterman** [comment] 2021-03-03 02:35
This might be something you have to debug yourself -- it sounds like not an error with the scraper so much as an issue with your file formatting.  The solution you suggest won't work; the intention of those lines is to extract the work_id (which is the first column) and name the text file after the id; if you add the entire row to the filename, you'll get an extremely long, nonsense name.  Without your specific files or system versions, I can't say for sure what is going on, but it's likely a misplaced empty row in your CSV.  Does it end with an extra new line?  Did you reformat it between outputting it from the fic script and inputting it here?  Check for stray lines, and if that isn't the problem I'd suggest adding some breakpoints and inspecting your output as it runs to find where in the file it's breaking.

**Comment by bloodconfetti** [comment] 2021-03-03 03:20
I haven't altered the produced csv. I only changed what program it opens with. And I have it located exactly where the .py program put it in the first place.

I do also note that the csv, in Notepad at least, doubles the quotation marks on all dialogue.

Maybe it just doesn't like the programs I use. I wonder what you open your csv files in? Maybe that is worthy of note somewhere. I'll see what I can do. Appreciate you!

**Comment by ssterman** [comment] 2021-03-03 04:52
I just pushed a quick change that should safely handle the empty row issue, in case that is what is affecting your files.  Pull the latest version and let me know if that helps at all.  

(the doubled quotation marks are important to csv formatting)

**Comment by bloodconfetti** [comment] 2021-03-03 05:32
That did work! Thank you so much for whatever change you implemented.

Overall, I got 1,135 fics out of the 15k (less locked fics.) I really appreciate this program.

I do notice that none of the title/author/tag data transfers into the individual fic files. I suppose one should just cross-reference the ID number title of a document with what's in the CSV. But if that's a feature request you think would be worth me making, I would gladly put it out there.

Thank you so much for your expertise and advice! (Didn't realize that about the quotation marks, but see where they're reduced in the actual fic text files. Awesome!)

**Comment by ssterman** [comment] 2021-03-04 00:07
Metadata isn't transferred into the text files intentionally -- the text files are just the stories, so they can be directly used with text analysis programs.   I would recommend exactly what you described: cross reference the IDs with the CSV.  

I'm glad the scraper is useful!

**Closed by ssterman** 2021-03-04 00:07 UTC
